export default model = {
	groupMemberCount: 4,
	numberOfParticipants: 4,
	EventId: 75537204,
	TimeStamp: '2020-04-08T18:01:04.363176500Z',
	Version: 4,
	Killer: {
		AverageItemPower: 1146.82678,
		Equipment: {
			MainHand: [Object],
			OffHand: null,
			Head: [Object],
			Armor: [Object],
			Shoes: [Object],
			Bag: [Object],
			Cape: [Object],
			Mount: [Object],
			Potion: [Object],
			Food: [Object],
		},
		Inventory: [],
		Name: 'PRIMA1945',
		Id: 'LYn_SfvcS6iWYb0Mtwbtnw',
		GuildName: 'Cursed Forge',
		GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
		AllianceName: '',
		AllianceId: '',
		AllianceTag: '',
		Avatar: 'AVATAR_HARVESTER_01',
		AvatarRing: 'AVATARRING_ADC_MAR2019',
		DeathFame: 0,
		KillFame: 1816308,
		FameRatio: 18163079.73,
		LifetimeStatistics: {
			PvE: [Object],
			Gathering: [Object],
			Crafting: [Object],
			CrystalLeague: 0,
			Timestamp: null,
		},
	},
	Victim: {
		AverageItemPower: 1159.30164,
		Equipment: {
			MainHand: [Object],
			OffHand: [Object],
			Head: [Object],
			Armor: [Object],
			Shoes: [Object],
			Bag: [Object],
			Cape: [Object],
			Mount: [Object],
			Potion: null,
			Food: [Object],
		},
		Inventory: [
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
			[Object],
		],
		Name: 'Moemoekanojo',
		Id: 'c9qyjZReTii_sGPL7xDAtA',
		GuildName: 'Real Bears',
		GuildId: 'kv7ez248Th2_BInR0dHdWg',
		AllianceName: 'Some1',
		AllianceId: 'b4LVDi-4TxKoYZ7mhjcL7w',
		AllianceTag: '',
		Avatar: 'AVATAR_BEAR_01',
		AvatarRing: 'AVATARRING_ADC_AUG2019',
		DeathFame: 7265234,
		KillFame: 0,
		FameRatio: 0,
		LifetimeStatistics: {
			PvE: [Object],
			Gathering: [Object],
			Crafting: [Object],
			CrystalLeague: 0,
			Timestamp: null,
		},
	},
	TotalVictimKillFame: 7265234,
	Location: null,
	Participants: [
		{
			AverageItemPower: 1023.34833,
			Equipment: [Object],
			Inventory: [],
			Name: 'Domestos6B6',
			Id: '4zn5fELYRFa_n3-Mk95Mhg',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_WOLF_01',
			AvatarRing: 'AVATARRING_ADC_APR2019',
			DeathFame: 0,
			KillFame: 0,
			FameRatio: 0,
			LifetimeStatistics: [Object],
			DamageDone: 1483,
			SupportHealingDone: 0,
		},
		{
			AverageItemPower: 1251.47168,
			Equipment: [Object],
			Inventory: [],
			Name: 'ArchGrey',
			Id: '7vMJXwKtS9OV7G5kXEzCOw',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_WOLF_01',
			AvatarRing: 'AVATARRING_ADC_JAN2019',
			DeathFame: 0,
			KillFame: 0,
			FameRatio: 0,
			LifetimeStatistics: [Object],
			DamageDone: 1268,
			SupportHealingDone: 0,
		},
		{
			AverageItemPower: 1209.7533,
			Equipment: [Object],
			Inventory: [],
			Name: 'Byhaya',
			Id: 'XCyCZensR9yeK2kGu94Kuw',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_MORGANA_01',
			AvatarRing: 'AVATARRING_ADC_APR2019',
			DeathFame: 0,
			KillFame: 0,
			FameRatio: 0,
			LifetimeStatistics: [Object],
			DamageDone: 349,
			SupportHealingDone: 0,
		},
		{
			AverageItemPower: 1146.82678,
			Equipment: [Object],
			Inventory: [],
			Name: 'PRIMA1945',
			Id: 'LYn_SfvcS6iWYb0Mtwbtnw',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_HARVESTER_01',
			AvatarRing: 'AVATARRING_ADC_MAR2019',
			DeathFame: 0,
			KillFame: 0,
			FameRatio: 0,
			LifetimeStatistics: [Object],
			DamageDone: 296,
			SupportHealingDone: 0,
		},
	],
	GroupMembers: [
		{
			AverageItemPower: 0,
			Equipment: [Object],
			Inventory: [],
			Name: 'ArchGrey',
			Id: '7vMJXwKtS9OV7G5kXEzCOw',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_WOLF_01',
			AvatarRing: 'AVATARRING_ADC_JAN2019',
			DeathFame: 0,
			KillFame: 1816308,
			FameRatio: 18163079.73,
			LifetimeStatistics: [Object],
		},
		{
			AverageItemPower: 0,
			Equipment: [Object],
			Inventory: [],
			Name: 'PRIMA1945',
			Id: 'LYn_SfvcS6iWYb0Mtwbtnw',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_HARVESTER_01',
			AvatarRing: 'AVATARRING_ADC_MAR2019',
			DeathFame: 0,
			KillFame: 1816308,
			FameRatio: 18163079.73,
			LifetimeStatistics: [Object],
		},
		{
			AverageItemPower: 0,
			Equipment: [Object],
			Inventory: [],
			Name: 'Domestos6B6',
			Id: '4zn5fELYRFa_n3-Mk95Mhg',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_WOLF_01',
			AvatarRing: 'AVATARRING_ADC_APR2019',
			DeathFame: 0,
			KillFame: 1816308,
			FameRatio: 18163079.73,
			LifetimeStatistics: [Object],
		},
		{
			AverageItemPower: 0,
			Equipment: [Object],
			Inventory: [],
			Name: 'AirTrix',
			Id: 'ypsJi4fHTo6reFmgduIQ9g',
			GuildName: 'Cursed Forge',
			GuildId: 'i6l2YkF_QtiPSDFA8uRAvQ',
			AllianceName: '',
			AllianceId: '',
			AllianceTag: '',
			Avatar: 'AVATAR_04',
			AvatarRing: 'RING1',
			DeathFame: 0,
			KillFame: 1816308,
			FameRatio: 18163079.73,
			LifetimeStatistics: [Object],
		},
	],
	GvGMatch: null,
	BattleId: 75537204,
	KillArea: 'OPEN_WORLD',
	Type: 'KILL',
};
